name: Deploy FastAPI to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy files via SSH
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: "."
          target: "/var/www/vinogradovnikita.ru"

      - name: Run deploy script on server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /var/www/vinogradovnikita.ru
            python3 -m venv venv
            source venv/bin/activate
            pip install -r requirements.txt
            # Остановить старый процесс (если был)
            pkill -f 'uvicorn' || true
            # Запустить FastAPI (замени main:app на свой путь)
            nohup venv/bin/uvicorn main:app --host 0.0.0.0 --port 80 &
